name: Lint and Fix 

on:
  push:
    branches: [master]

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Lint and Fix 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Commit changes
      run: |
        git config user.name "buffeinstein"
        git config user.email "ambikatiwari999@gmail.com
        git add -u
        git commit -m "Automatically fix linting issues"
        git push
